data:
  masks:
    masks_path: '../openmask3d/output/2024-05-13-22-42-53-experiment/scene_example_masks.pt' #scannet200
  camera:
    poses_path: '../openmask3d/resources/scene_example/pose/'
    intrinsic_path: '../openmask3d/resources/scene_example/intrinsic/intrinsic_color.txt'
    intrinsic_resolution: [968, 1296]
  depths:
    depths_path: '../openmask3d/resources/scene_example/depth/'
    depths_ext: '.png'
    depth_scale: 1000
  images:
    images_path: '../openmask3d/resources/scene_example/color/'  
    images_ext: '.jpg'
  point_cloud_path: '../openmask3d/resources/scene_example/scene_example.ply'

openmask3d:
  top_k: 5
  multi_level_expansion_ratio: 0.1
  num_of_levels: 3
  vis_threshold: 0.2
  frequency: 10
  num_random_rounds: 10
  num_selected_points: 5

external:
  sam_checkpoint: '../openmask3d/resources/sam_vit_b_01ec64.pth' #'../openmask3d/resources/sam_vit_h_4b8939.pth'
  sam_model_type: 'vit_b' #'vit_h'
  clip_model: 'ViT-L/14@336px'

output:
  experiment_name: 'experiment'
  output_directory: 'output/'
  save_crops: True

gpu:
  optimize_gpu_usage: True