mp3dcat = [
    "void",
    "wall",
    "floor",
    "chair",
    "door",
    "table",
    "picture",
    "cabinet",
    "cushion",
    "window",
    "sofa",
    "bed",
    "curtain",
    "chest_of_drawers",
    "plant",
    "sink",
    "stairs",
    "ceiling",
    "toilet",
    "stool",
    "towel",
    "mirror",
    "tv_monitor",
    "shower",
    "column",
    "bathtub",
    "counter",
    "fireplace",
    "lighting",
    "beam",
    "railing",
    "shelving",
    "blinds",
    "gym_equipment",
    "seating",
    "board_panel",
    "furniture",
    "appliances",
    "clothes",
    "objects",
    "floor lamp",
    "box",
    "red pillow",
    "television",
]

mp3dcat_s = [
    "wall",
    "floor",
    "chair", #3
    "door", #4
    "table", #5
    "cabinet",
    "window",
    "sofa", #8
    "curtain",
    "plant",#11
    "sink",
    "ceiling",
    "stool", #15凳子
    "railing",
    "furniture",#20
    'air conditioner',
    'faucet',
    'refrigerator',
    'pillow',
    'Table lamp',
]
mp3dcat_ss = [
    "void",
    "wall",
    "floor",
    "chair", #3
    "door", #4
    "table", #5
    "cabinet",
    "window",
    "sofa", #8
    "bed",
    "curtain",
    "plant",#11
    "sink",
    "ceiling",
    "toilet", #14
    "stool", #15凳子
    "mirror",
    "bathtub",#17
    "lighting",
    "railing",
    "furniture",#20
    'air conditioner',
    'Washing machine',
    'faucet',
    'refrigerator',
    'pillow',
    'Table lamp',
    'socket',

]
ithor_s = [
    'Arm Chair',
'Boots',
'Box',
'Coffee Table',
'Credit Card',
'Drawer',
'Floor',
'Floor Lamp',
'Garbage Can',
'House Plant',
'Key Chain',
'Laptop',
'Light Switch',
'Newspaper',
'Painting',
'Pen',
'Pencil',
'Pillow',
'Remote Control',
'Shelf',
'Side Table',
'Sofa',
'Statue',
'Television',
'Tissue Box',
'TV Stand',
'WateringCan',
'Window',

]
ithor_obj=[
    'Alarm Clock',
    'Aluminum Foil',
    'Apple',
    'Arm Chair',
    'Baseball Bat',
    'Basket Ball',
    'Bathtub',
    'Bathtub Basin',
    'Bed',
    'Blinds',
    'Book',
    'Boots',
    'Bottle',
    'Bowl',
    'Box',
    'Bread',
    'Butter Knife',
    'Cabinet',
    'Candle',
    'CD',
    'Cell Phone',
    'Chair',
    'Cloth',
    'Coffee Machine',
    'Coffee Table',
    'Counter Top',
    'Credit Card',
    'Cup',
    'Curtains',
    'Desk',
    'Desk Lamp',
    'Desktop',
    'Dining Table',
    'Dish Sponge',
    'Dog Bed',
    'Drawer',
    'Dresser',
    'Dumbbell',
    'Egg',
    'Faucet',
    'Floor',
    'Floor Lamp',
    'Footstool',
    'Fork',
    'Fridge',
    'Garbage Bag',
    'Garbage Can',
    'Hand Towel',
    'Hand Towel Holder',
    'House Plant',
    'Kettle',
    'Key Chain',
    'Knife',
    'Ladle',
    'Laptop',
    'Laundry Hamper',
    'Lettuce',
    'Light Switch',
    'Microwave',
    'Mirror',
    'Mug',
    'Newspaper',
    'Ottoman',
    'Painting',
    'Pan',
    'Paper Towel Roll',
    'Pen',
    'Pencil',
    'Pepper Shaker',
    'Pillow',
    'Plate',
    'Plunger',
    'Poster',
    'Pot',
    'Potato',
    'Remote Control',
    'Room Decor',
    'Safe',
    'Salt Shaker',
    'Scrub Brush',
    'Shelf',
    'Shelving Unit',
    'Shower Curtain',
    'Shower Door',
    'Shower Glass',
    'Shower Head',
    'Side Table',
    'Sink',
    'Sink Basin',
    'Soap Bar',
    'Soap Bottle',
    'Sofa',
    'Spatula',
    'Spoon',
    'Spray Bottle',
    'Statue',
    'Stool',
    'Stove Burner',
    'Stove Knob',
    'Table Top Decor',
    'Teddy Bear',
    'Television',
    'Tennis Racket',
    'Tissue Box',
    'Toaster',
    'Toilet',
    'Toilet Paper',
    'Toilet Paper Hanger',
    'Tomato',
    'Towel',
    'Towel Holder',
    'TV Stand',
    'Vacuum Cleaner',
    'Vase',
    'Watch',
    'Watering Can',
    'Window',
    'Wine Bottle',
]
