defaults:
  - data_paths: default

scene_names:
  -   jh4fc5c5qoQ #Chesterbrook ## 5LpN3gDmAk7
data_cfg:
  rgb: true
  depth: true
  semantic: true
  resolution:
    w: 1080
    h: 720
  camera_height: 1.2