defaults:
  - data_paths: default
  - map_config: vlmaps
  - params: default
  - _self_
nav:
  valid_range: 1
  vis: True #False
  tasks_per_scene: 20
scene_id: 0

# indexing params
decay_rate: 0.01
index_2d: False #True #
init_categories: True